[SDK-3680] README redesign
auth0/auth0-java pull request #459
Opened 2022-10-14 00:02 UTC by jimmyjames

Updates the README per the new design specs.

Notes:
- There was no existing `EXAMPLES.md`, so I created one and populated with the example content that was contained in the README
- The README had a lot of API-level documentation within it. I removed most of it, as it is covered in the API reference documentation now more clearly linked-to in the README.
- This PR does not the banner, as we are awaiting final design. We will either update this PR when it is available, or follow-up with an additional PR.

2022-10-14 10:39 UTC, frederikprijck requested changes

2022-10-14 10:39 UTC, frederikprijck commented on EXAMPLES.md
> +
```suggestion

```

2022-10-14 10:41 UTC, frederikprijck commented on EXAMPLES.md
> +
As mentioned on slack, we are getting rid of some of the organizations marketing text, as we are already point to the docs above.

2022-10-17 08:37 UTC, frederikprijck commented on EXAMPLES.md
> +
It looks like this is still present, is that intentional?

2022-10-17 14:13 UTC, frederikprijck submitted a review, later dismissed

2022-10-24 16:07 UTC, ewanharris commented on README.md
> +- [Auth0's code of conduct guidelines]((https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md))
Extra brackets here
```suggestion
- [Auth0's code of conduct guidelines](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
```

2022-10-25 09:06 UTC, frederikprijck approved these changes

2022-10-25 19:59 UTC, merged